import { Card } from "../components/Card";
import { API_URL, BOT_VERSION } from "../lib/api";
import { gbp, pct, tone } from "../lib/format";
import type { ActionFn, AnyObj, BuySizeMode } from "../lib/types";

export function AdminPage(props: AnyObj & { action: ActionFn }) {
  const { data, banking, logs, dynamicScanner, dynamicRows, strategySettings, positionSettings, action, tradingCapInput, setTradingCapInput, tradingCapSaving, saveTradingCap, manualBaselineInput, setManualBaselineInput, baselineSaving, setManualBaseline, strategyStrictness, setStrategyStrictness, strategySaving, saveStrategy, maxPositionsInput, setMaxPositionsInput, positionsSaving, saveMaxPositions, buySizeMode, saveBuySizeMode, replayCapInput, setReplayCapInput, replayLoading, replayResult, runBacktestReplay } = props;
  return <main className="grid two">
    <Card title="AI Risk Profile"><label className="field"><span>Conservative ← Balanced → Aggressive</span><input type="range" min="0" max="2" step="1" value={strategyStrictness} onChange={(e) => setStrategyStrictness(Number(e.target.value))}/></label><div className="summary"><div><span>Current</span><b>{["Conservative", "Balanced", "Aggressive"][strategyStrictness]}</b></div><div><span>A+ gate</span><b>{Number(strategySettings?.aPlusMinConfidence ?? data?.aPlusMinConfidence ?? 0).toFixed(2)}</b></div></div><button onClick={saveStrategy} disabled={strategySaving}>{strategySaving ? "Saving..." : "Save Risk Profile"}</button></Card>
    <Card title="Capital & Position Limits"><label className="field"><span>Trading cap (£)</span><input value={tradingCapInput} onChange={(e) => setTradingCapInput(e.target.value)} inputMode="decimal"/></label><button onClick={saveTradingCap} disabled={tradingCapSaving}>{tradingCapSaving ? "Saving..." : "Save Trading Cap"}</button><label className="field"><span>Maximum open positions: {maxPositionsInput}</span><input type="range" min="1" max="10" value={maxPositionsInput} onChange={(e) => setMaxPositionsInput(Number(e.target.value))}/></label><button onClick={saveMaxPositions} disabled={positionsSaving}>{positionsSaving ? "Saving..." : "Save Position Limit"}</button><div className="actions admin-section"><button className={buySizeMode === "partial" ? "active" : "ghost"} onClick={() => saveBuySizeMode("partial" as BuySizeMode)}>Partial Buy</button><button className={buySizeMode === "full" ? "active" : "ghost"} onClick={() => saveBuySizeMode("full" as BuySizeMode)}>Full Buy</button></div></Card>
    <Card title="Scanner & Universe Tools"><div className="actions"><button className="purple" onClick={() => action("/refresh-universe")}>Refresh Universe</button></div><div className="summary"><div><span>Dynamic picks</span><b>{Number(data?.autoUniverse?.dynamicPickCount || dynamicRows.length || 0)}</b></div><div><span>Active symbols</span><b>{Number(data?.autoUniverse?.activeSymbols?.length || 0)}</b></div><div><span>Source</span><b>{dynamicScanner?.source || "market movers"}</b></div></div></Card>
    <Card title="Reports Maintenance"><div className="actions"><button onClick={() => action("/backfill-trades")}>Backfill Past Trades</button><button onClick={() => action("/backfill-trades-limited")}>Quick Backfill</button><button onClick={() => action("/rebuild-closed-trades")}>Rebuild Closed Trades</button><button className="danger" onClick={() => confirm("Reset reporting baseline to current equity?") && action("/reset-baseline")}>Reset Baseline</button></div><label className="field"><span>Manual baseline (£)</span><input value={manualBaselineInput} onChange={(e) => setManualBaselineInput(e.target.value)}/></label><button onClick={setManualBaseline} disabled={baselineSaving}>{baselineSaving ? "Saving..." : "Set Manual Baseline"}</button></Card>
    <Card title="Backtest / Paper Replay"><label className="field"><span>Replay cap (£)</span><input value={replayCapInput} onChange={(e) => setReplayCapInput(e.target.value)}/></label><button onClick={runBacktestReplay} disabled={replayLoading}>{replayLoading ? "Running..." : "Run Replay"}</button>{replayResult && <div className="summary admin-section"><div><span>Trades</span><b>{replayResult?.tradesTested || 0}</b></div><div><span>Win rate</span><b>{pct(Number(replayResult?.winRate || 0) * 100)}</b></div><div><span>PnL</span><b className={tone(replayResult?.replayPnlGbp)}>{gbp(replayResult?.replayPnlGbp)}</b></div></div>}</Card>
    <Card title="Developer Diagnostics" wide><div className="ai-grid"><div><h3>Recent Logs</h3><div className="log-list">{logs.slice(-80).reverse().map((line: string, index: number) => <div key={index}>{line}</div>)}{!logs.length && <p className="muted">No logs returned.</p>}</div></div><div><h3>Runtime Snapshot</h3><pre>{JSON.stringify({ api: API_URL, version: BOT_VERSION, botEnabled: data?.botEnabled, market: data?.market, strategySettings, positionSettings, banking, autoUniverse: data?.autoUniverse }, null, 2)}</pre></div></div></Card>
  </main>;
}
