import { useCallback, useEffect, useState } from "react";
import { Card } from "../components/Card";
import { API_URL, readJson } from "../lib/api";
import type { AnyObj } from "../lib/types";

const move = (value:any) => value == null ? "—" : `${Number(value) >= 0 ? "+" : ""}${Number(value).toFixed(2)}%`;
const label = (value:string) => value === "GOOD_BLOCK" ? "GOOD BLOCK" : value === "MISSED_WINNER" ? "MISSED WINNER" : "NEUTRAL";
const gap = (r:AnyObj) => {
  const nm=r?.nearMiss; if(!nm?.isNearMiss) return "—";
  const n=Number(nm.gap||0); const metric=String(nm.metric||"");
  if(metric==="win_rate") return `${(n*100).toFixed(1)}pp`;
  if(metric==="quality"||metric==="spread"||metric==="momentum") return n.toFixed(4);
  if(metric==="expectancy_pct") return `${n.toFixed(2)}pp`;
  return n.toFixed(2);
};
export function AuditPage({ authToken }: { authToken:string }) {
  const [data,setData]=useState<AnyObj>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{ setLoading(true); setError(""); try { const r=await fetch(`${API_URL}/v17/decision-audit?days=7`,{cache:"no-store",headers:{"X-Auth-Token":authToken,"x-api-key":authToken}}); const j=await readJson(r); if(!r.ok) throw new Error(j?.detail||j?.error||`HTTP ${r.status}`); setData(j||{}); } catch(e:any){setError(e?.message||"Decision audit unavailable");} finally{setLoading(false);} },[authToken]);
  useEffect(()=>{load(); const id=window.setInterval(load,30000); return()=>window.clearInterval(id);},[load]);
  const gates=Array.isArray(data?.gates)?data.gates:[]; const recent=Array.isArray(data?.recent)?data.recent:[];
  const learning=data?.learning||{}; const nearMissProfiles=Array.isArray(learning?.nearMissProfiles)?learning.nearMissProfiles:[]; const missedEpisodes=Array.isArray(learning?.missedMoveEpisodes)?learning.missedMoveEpisodes:[];
  return <main className="grid two"><Card title="V18.2.26 Decision Audit + Near-Miss Learning" wide><div className="actions"><button onClick={load} disabled={loading}>{loading?"Loading...":"Refresh Audit"}</button></div>{error&&<p className="notice loss">{error}</p>}<div className="summary"><div><span>Window</span><b>7 days</b></div><div><span>Pending checkpoints</span><b>{Number(data?.pendingCheckpoints||0)}</b></div><div><span>Missed winner</span><b>≥ +{Number(data?.thresholds?.missedWinnerPct||1).toFixed(2)}%</b></div><div><span>Good block</span><b>≤ {Number(data?.thresholds?.goodBlockPct||-0.5).toFixed(2)}%</b></div></div><p className="notice">Advisory only. Near-miss learning measures borderline rejections and repeated missed moves, but it cannot loosen a live gate or place an order.</p></Card>
  <Card title="Gate Effectiveness — Last 7 Days" wide><div className="table-wrap"><table><thead><tr><th>Gate</th><th>Blocked</th><th>Good blocks</th><th>Missed winners</th><th>Neutral</th><th>Effectiveness</th><th>Avg 1h</th></tr></thead><tbody>{gates.map((g:AnyObj)=><tr key={g.stage}><td><b>{String(g.stage||"unknown").toUpperCase()}</b></td><td>{g.blocked}</td><td>{g.good_blocks}</td><td>{g.missed_winners}</td><td>{g.neutral}</td><td>{Number(g.effectivenessPct||0).toFixed(1)}%</td><td>{move(g.avg_1h_return_pct)}</td></tr>)}{!gates.length&&<tr><td colSpan={7}>No completed rejection evidence yet. It will populate as new rejected candidates reach their checkpoints.</td></tr>}</tbody></table></div></Card>
  <Card title="Near-Miss Learning — De-duplicated Evidence" wide><p className="notice">Repeated scans are collapsed into 30-minute episodes before learning. Evidence is kept symbol + gate + reason aware. REVIEW requires at least two de-duplicated missed-winner episodes and more misses than good blocks; nothing here changes a live threshold automatically.</p><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Gate</th><th>Reason</th><th>Episodes</th><th>Scan rows</th><th>Missed</th><th>Good</th><th>Miss rate</th><th>Avg gap</th><th>Evidence</th></tr></thead><tbody>{nearMissProfiles.map((r:AnyObj)=><tr key={`${r.symbol}-${r.stage}-${r.reasonBucket}`}><td><b>{r.symbol}</b></td><td>{r.stage}</td><td>{String(r.reasonBucket||"").replaceAll("_"," ")}</td><td>{r.episodes}</td><td>{r.scanRows}</td><td>{r.missedWinnerEpisodes}</td><td>{r.goodBlockEpisodes}</td><td>{Number(r.missRatePct||0).toFixed(1)}%</td><td>{Number(r.avgGap||0).toFixed(4)}</td><td><b>{r.evidence}</b></td></tr>)}{!nearMissProfiles.length&&<tr><td colSpan={10}>No numeric borderline-gate evidence yet.</td></tr>}</tbody></table></div></Card>
  <Card title="Missed Move Episodes — Repeated Scans Count Once" wide><p className="notice">This is the de-duplicated view of missed winners. A sustained move in the same symbol within 30 minutes is treated as one opportunity episode rather than many separate mistakes.</p><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Start</th><th>End</th><th>Scans</th><th>Peak move</th><th>Gates seen</th><th>Reasons seen</th></tr></thead><tbody>{missedEpisodes.map((r:AnyObj,i:number)=><tr key={`${r.symbol}-${r.startAt}-${i}`}><td><b>{r.symbol}</b></td><td>{r.startAt?new Date(r.startAt).toLocaleString():"—"}</td><td>{r.endAt?new Date(r.endAt).toLocaleString():"—"}</td><td>{r.scanCount}</td><td>{move(r.peakReturnPct)}</td><td>{Array.isArray(r.gates)?r.gates.join(", "):"—"}</td><td>{Array.isArray(r.reasons)?r.reasons.join(", ").replaceAll("_"," "):"—"}</td></tr>)}{!missedEpisodes.length&&<tr><td colSpan={7}>No de-duplicated missed-winner episodes yet.</td></tr>}</tbody></table></div></Card>
  <Card title="Today’s Rejected Opportunities — Full Market Session" wide><p className="notice">Showing all rejected opportunities from today’s 09:30 ET market open. BORDERLINE means the decision missed a numeric gate by only the configured near-miss tolerance; it is evidence only.</p><div className="table-wrap"><table><thead><tr><th>Time</th><th>Symbol</th><th>Gate</th><th>15m</th><th>30m</th><th>1h</th><th>2h</th><th>Near miss</th><th>Gap</th><th>Verdict</th><th>Reason</th></tr></thead><tbody>{recent.map((r:AnyObj)=><tr key={r.decision_id}><td>{r.decision_at?new Date(r.decision_at).toLocaleString():"—"}</td><td><b>{r.symbol}</b></td><td>{r.stage}</td><td>{move(r.return_15m)}</td><td>{move(r.return_30m)}</td><td>{move(r.return_1h)}</td><td>{move(r.return_2h)}</td><td><b>{r?.nearMiss?.isNearMiss?"BORDERLINE":"—"}</b></td><td>{gap(r)}</td><td><b>{label(r.classification)}</b></td><td>{r.reason}</td></tr>)}{!recent.length&&<tr><td colSpan={11}>Waiting for the first audited rejection.</td></tr>}</tbody></table></div></Card></main>;
}
