import { useCallback, useEffect, useState } from "react";
import { Card } from "../components/Card";
import { API_URL, readJson } from "../lib/api";
import type { AnyObj } from "../lib/types";

const move = (value:any) => value == null ? "—" : `${Number(value) >= 0 ? "+" : ""}${Number(value).toFixed(2)}%`;
const label = (value:string) => value === "GOOD_BLOCK" ? "GOOD BLOCK" : value === "MISSED_WINNER" ? "MISSED WINNER" : "NEUTRAL";
export function AuditPage({ authToken }: { authToken:string }) {
  const [data,setData]=useState<AnyObj>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{ setLoading(true); setError(""); try { const r=await fetch(`${API_URL}/v17/decision-audit?days=7`,{cache:"no-store",headers:{"X-Auth-Token":authToken,"x-api-key":authToken}}); const j=await readJson(r); if(!r.ok) throw new Error(j?.detail||j?.error||`HTTP ${r.status}`); setData(j||{}); } catch(e:any){setError(e?.message||"Decision audit unavailable");} finally{setLoading(false);} },[authToken]);
  useEffect(()=>{load(); const id=window.setInterval(load,30000); return()=>window.clearInterval(id);},[load]);
  const gates=Array.isArray(data?.gates)?data.gates:[]; const recent=Array.isArray(data?.recent)?data.recent:[];
  return <main className="grid two"><Card title="V17.9 Decision Audit" wide><div className="actions"><button onClick={load} disabled={loading}>{loading?"Loading...":"Refresh Audit"}</button></div>{error&&<p className="notice loss">{error}</p>}<div className="summary"><div><span>Window</span><b>7 days</b></div><div><span>Pending checkpoints</span><b>{Number(data?.pendingCheckpoints||0)}</b></div><div><span>Missed winner</span><b>≥ +{Number(data?.thresholds?.missedWinnerPct||1).toFixed(2)}%</b></div><div><span>Good block</span><b>≤ {Number(data?.thresholds?.goodBlockPct||-0.5).toFixed(2)}%</b></div></div><p className="notice">Advisory only. This measures whether rejected entries later moved in the bot's favour; it cannot loosen a live gate or place an order.</p></Card>
  <Card title="Gate Effectiveness — Last 7 Days" wide><div className="table-wrap"><table><thead><tr><th>Gate</th><th>Blocked</th><th>Good blocks</th><th>Missed winners</th><th>Neutral</th><th>Effectiveness</th><th>Avg 1h</th></tr></thead><tbody>{gates.map((g:AnyObj)=><tr key={g.stage}><td><b>{String(g.stage||"unknown").toUpperCase()}</b></td><td>{g.blocked}</td><td>{g.good_blocks}</td><td>{g.missed_winners}</td><td>{g.neutral}</td><td>{Number(g.effectivenessPct||0).toFixed(1)}%</td><td>{move(g.avg_1h_return_pct)}</td></tr>)}{!gates.length&&<tr><td colSpan={7}>No completed rejection evidence yet. It will populate as new rejected candidates reach their checkpoints.</td></tr>}</tbody></table></div></Card>
  <Card title="Recent Rejected Opportunities" wide><div className="table-wrap"><table><thead><tr><th>Time</th><th>Symbol</th><th>Gate</th><th>15m</th><th>30m</th><th>1h</th><th>2h</th><th>Verdict</th><th>Reason</th></tr></thead><tbody>{recent.map((r:AnyObj)=><tr key={r.decision_id}><td>{r.decision_at?new Date(r.decision_at).toLocaleString():"—"}</td><td><b>{r.symbol}</b></td><td>{r.stage}</td><td>{move(r.return_15m)}</td><td>{move(r.return_30m)}</td><td>{move(r.return_1h)}</td><td>{move(r.return_2h)}</td><td><b>{label(r.classification)}</b></td><td>{r.reason}</td></tr>)}{!recent.length&&<tr><td colSpan={9}>Waiting for the first audited rejection.</td></tr>}</tbody></table></div></Card></main>;
}
