import { Line, LineChart, ResponsiveContainer, Tooltip } from "recharts";
import { Card } from "../components/Card";
import { gbp, pct, tone, usd } from "../lib/format";
import type { ActionFn, AnyObj } from "../lib/types";

export function ExplorerPage({ data, stockQuery, setStockQuery, stockResults, setStockResults, stockSearchLoading, searchStocks, action }: { data: AnyObj; stockQuery: string; setStockQuery: (value: string) => void; stockResults: AnyObj[]; setStockResults: (value: AnyObj[]) => void; stockSearchLoading: boolean; searchStocks: (query?: string) => Promise<void>; action: ActionFn }) {
  const adaptive = data?.adaptiveUniverse || {};
  const adaptiveRows = Array.isArray(adaptive?.rows) ? adaptive.rows : [];
  return <main><Card title="Adaptive Open-Market Universe"><div className="adaptive-summary"><div><strong>{adaptiveRows.length || adaptive?.activeSymbols?.length || 0}</strong><span>Active scan slots</span></div><div><strong>{adaptive?.discoveryCount ?? 0}</strong><span>Fresh discoveries</span></div><div><strong>{adaptive?.coreCount ?? 0}</strong><span>Core anchors</span></div><div><strong>{Math.round(Number(adaptive?.refreshSeconds || 0) / 60) || 30}m</strong><span>Rotation interval</span></div></div><div className="adaptive-grid">{adaptiveRows.map((row: AnyObj) => <div className="adaptive-chip" key={row.symbol}><div><strong>{row.symbol}</strong><span className={`adaptive-source ${String(row.adaptiveSource || "").toLowerCase()}`}>{row.adaptiveSource || "ACTIVE"}</span></div><small>{String(row.reason || "").split("|")[0].trim()}</small></div>)}</div><div className="search-actions"><button onClick={() => action("/adaptive-universe/refresh")}>Refresh Open Market</button></div></Card><Card title="Market Explorer"><div className="search-row"><input value={stockQuery} onChange={(event) => { const value = event.target.value; setStockQuery(value); if (value.trim().length >= 2) searchStocks(value); if (!value.trim()) setStockResults([]); }} onKeyDown={(event) => event.key === "Enter" && searchStocks()} placeholder="Search ticker or company, e.g. AMD"/><button onClick={() => searchStocks()}>{stockSearchLoading ? "Searching..." : "Search"}</button></div><div className="search-results">{stockResults.map((stock) => <article className="search-card" key={stock.symbol}><div className="search-main"><div className="logo-circle">{stock.symbol.slice(0, 2)}</div><div><h3>{stock.name}</h3><p>{stock.symbol} · NASDAQ/NYSE</p></div></div><div className="search-price"><strong>{usd(stock.price)}</strong><span className={tone(stock.changePct)}>{pct(stock.changePct)}</span><small>{gbp(stock.priceGbp)}</small></div><div className="mini-chart">{Array.isArray(stock.history) && stock.history.length > 1 ? <ResponsiveContainer width="100%" height="100%"><LineChart data={stock.history.map((point: AnyObj, index: number) => ({ ...point, index }))}><Line type="monotone" dataKey="value" stroke="#38bdf8" dot={false} strokeWidth={2}/><Tooltip formatter={(value: any) => usd(value)}/></LineChart></ResponsiveContainer> : <p className="muted">Preview builds while you search.</p>}</div><div className="search-actions"><button onClick={() => action(`/custom-buy/${stock.symbol}`)}>Buy</button><button className="ghost" onClick={() => action(`/add-to-universe/${stock.symbol}`)}>Pin</button><button className="danger" onClick={() => action(`/remove-from-universe/${stock.symbol}`)}>Remove</button></div></article>)}{!stockResults.length && <p className="muted">Search a symbol to preview price, movement and chart.</p>}</div></Card></main>;
}
