import { useCallback, useEffect, useState } from "react";
import { Card } from "../components/Card";
import { API_URL, readJson } from "../lib/api";
import type { AnyObj } from "../lib/types";

const money=(v:any)=>`£${Number(v||0).toFixed(2)}`;
export function ObservatoryPage({authToken}:{authToken:string}){
 const [data,setData]=useState<AnyObj>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`${API_URL}/v18/performance-observatory?days=7`,{cache:"no-store",headers:{"X-Auth-Token":authToken,"x-api-key":authToken}});const j=await readJson(r);if(!r.ok||j?.ok===false)throw new Error(j?.detail||j?.error||`HTTP ${r.status}`);setData(j||{});}catch(e:any){setError(e?.message||"Observatory unavailable");}finally{setLoading(false);}},[authToken]);
 useEffect(()=>{load();},[load]); const t=data?.trading||{},p=data?.profitProtection||{},c=data?.profitCapture||{},a=data?.decisionAudit||{},g=data?.governance||{}; const exits=Array.isArray(data?.exits)?data.exits:[]; const gates=Array.isArray(a?.gates)?a.gates:[];
 return <main className="grid two">
  <Card title="V18.1 Evidence & Performance Observatory" wide><div className="actions"><button onClick={load} disabled={loading}>{loading?"Refreshing...":"Refresh Observatory"}</button></div>{error&&<p className="notice loss">{error}</p>}<p className="notice">Read-only evidence layer. It measures trading, protection, rejected opportunities, exits and V18 governance without changing a live rule.</p></Card>
  <Card title="Trading Performance"><div className="summary"><div><span>Realised P&L · 7d</span><b>{money(t.realisedPnlGbp)}</b></div><div><span>Closed trades</span><b>{Number(t.closedTrades||0)}</b></div><div><span>Win rate</span><b>{Number(t.winRatePct||0).toFixed(1)}%</b></div><div><span>Max realised drawdown</span><b>{money(t.maxRealisedDrawdownGbp)}</b></div><div><span>Avg winner</span><b>{money(t.avgWinnerGbp)}</b></div><div><span>Avg loser</span><b>{money(t.avgLoserGbp)}</b></div></div></Card>
  <Card title="Profit Protection"><div className="summary"><div><span>Banked profit</span><b>{money(p.bankedProfitGbp)}</b></div><div><span>Lifetime banked</span><b>{money(p.lifetimeBankedGbp)}</b></div><div><span>Working capital</span><b>{money(p.workingCapitalGbp)}</b></div><div><span>Protected baseline</span><b>{money(p.protectedBaselineGbp)}</b></div></div></Card>
  <Card title="Profit Capture"><div className="summary"><div><span>Replay trades measured</span><b>{Number(c.replayTradesMeasured||0)}</b></div><div><span>Average peak capture</span><b>{c.averagePeakCapturePct==null?"COLLECTING":`${Number(c.averagePeakCapturePct).toFixed(1)}%`}</b></div></div><p className="muted">Peak capture compares realised exit price with the highest recorded Trade Replay price after entry.</p></Card>
  <Card title="V18 Governance"><div className="summary"><div><span>Verdict</span><b>{g.verdict||"—"}</b></div><div><span>Evidence</span><b>{g.evidenceStrength||"—"}</b></div><div><span>Stability</span><b>{Number(g?.proposal?.stabilityCount||0)} / {Number(g?.proposal?.stabilityRequired||5)}</b></div><div><span>Board eligible</span><b>{g?.proposal?.promotionEligible?"YES":"NO"}</b></div></div><p>{g?.proposal?.text||"Collecting evidence."}</p></Card>
  <Card title="Decision Audit" wide><div className="table-wrap"><table><thead><tr><th>Gate</th><th>Blocked</th><th>Good blocks</th><th>Missed winners</th><th>Neutral</th><th>Effectiveness</th></tr></thead><tbody>{gates.map((x:AnyObj)=><tr key={x.stage}><td><b>{String(x.stage||"unknown").toUpperCase()}</b></td><td>{x.blocked}</td><td>{x.good_blocks}</td><td>{x.missed_winners}</td><td>{x.neutral}</td><td>{Number(x.effectivenessPct||0).toFixed(1)}%</td></tr>)}{!gates.length&&<tr><td colSpan={6}>Collecting V17.9 live-market rejection evidence.</td></tr>}</tbody></table></div></Card>
  <Card title="Exit Performance" wide><div className="table-wrap"><table><thead><tr><th>Exit reason</th><th>Trades</th><th>Win rate</th><th>Realised P&L</th></tr></thead><tbody>{exits.map((x:AnyObj)=><tr key={x.reason}><td><b>{x.reason}</b></td><td>{x.trades}</td><td>{Number(x.winRatePct||0).toFixed(1)}%</td><td>{money(x.pnlGbp)}</td></tr>)}{!exits.length&&<tr><td colSpan={4}>No closed trades in this evidence window yet.</td></tr>}</tbody></table></div></Card>
 </main>;
}
