import { Card } from "../components/Card";
import { Meter } from "../components/Meter";
import { gbp, pct, tone, usd } from "../lib/format";
import type { ActionFn, AnyObj, PositionStyleFn } from "../lib/types";

export function OverviewPage({ data, message, positions, trades, rate, bestCandidate, aiConfidence, marketRegime, riskLabel, currentAction, botHealth, aiReasons, positionSettings, fetchData, action, positionGlowStyle }: { data: AnyObj; message: string; positions: AnyObj[]; trades: AnyObj[]; rate: number; bestCandidate?: AnyObj; aiConfidence: number; marketRegime: string; riskLabel: string; currentAction: string; botHealth: number; aiReasons: string[]; positionSettings: AnyObj; fetchData: (force?: boolean) => Promise<void>; action: ActionFn; positionGlowStyle: PositionStyleFn }) {
  const maxPositions = Number(data?.maxPositions || positionSettings?.maxPositions || 0);
  return <main className="grid two">
    <Card title="AI Brain" className="hero-card decision-card"><div className="ai-grid"><div><div className="ai-status-line"><span>Market view</span><b>{marketRegime}</b></div><div className="ai-status-line"><span>Risk</span><b>{riskLabel}</b></div><div className="ai-status-line"><span>Current action</span><b>{currentAction}</b></div><div className="ai-status-line"><span>Open positions</span><b>{positions.length}/{maxPositions}</b></div></div><div><Meter value={aiConfidence} label="AI confidence"/><Meter value={botHealth} label="System health"/><p className="notice">{message}</p></div></div></Card>
    <Card title="Best Current Opportunity" className="decision-card">{bestCandidate?.symbol ? <><p className="eyebrow">Top-ranked candidate</p><h3 className="decision-symbol">{bestCandidate.symbol}</h3><div className="summary"><div><span>Confidence</span><b>{aiConfidence.toFixed(0)}%</b></div><div><span>Price</span><b>{bestCandidate?.price ? usd(bestCandidate.price) : "—"}</b></div><div><span>Movement</span><b className={tone(bestCandidate?.changePct || bestCandidate?.gap_pct)}>{pct(bestCandidate?.changePct ?? bestCandidate?.gap_pct ?? 0)}</b></div></div><ul className="reason-list">{aiReasons.length ? aiReasons.map((reason) => <li key={reason}>{reason}</li>) : <li>Waiting for the live scanner to provide detailed evidence.</li>}</ul></> : <p className="muted">No ranked opportunity is available yet. The card will populate when the scanner produces candidates.</p>}</Card>
    <Card title="Bot Controls"><div className="actions"><button onClick={() => fetchData(true)}>Refresh</button><button onClick={() => action("/manual-buy")}>Money Buy</button><button className="danger" onClick={() => action("/manual-sell")}>Sell Worst</button><button className="ghost" onClick={() => action("/pause")}>Pause</button><button onClick={() => action("/resume")}>Resume</button><button className="danger" onClick={() => confirm("Emergency sell all open positions?") && action("/emergency-sell")}>Emergency Sell All</button></div><p className="muted">Routine scanner and universe management stays automatic. Technical controls are in Admin.</p></Card>
    <Card title="Live Portfolio"><div className="summary"><div><span>Positions</span><b>{positions.length}</b></div><div><span>Next buy</span><b>{gbp(Number(data?.newPositionNotional || 0) * rate)}</b></div><div><span>Win rate</span><b>{pct(Number(data?.dbSummary?.winRate || 0) * 100)}</b></div><div><span>Available slots</span><b>{Math.max(0, maxPositions - positions.length)}</b></div></div><div className="position-list">{positions.slice(0, 3).map((p) => <article className="position" key={p.symbol} style={positionGlowStyle(p)}><div><h3>{p.symbol}</h3><p>{usd(p.price)} · Qty {Number(p.qty || 0).toFixed(4)}</p></div><div className="position-side"><b className={tone(p.pnl)}>{gbp(p.pnlGbp ?? Number(p.pnl || 0) * rate)} · {pct(p.pnlPct)}</b></div></article>)}{!positions.length && <p className="muted">No open positions.</p>}</div></Card>
    <Card title="Recent AI Activity" wide><div className="log-list">{trades.slice(-8).reverse().map((trade, index) => <div key={index}>{trade.time || "—"} · <b>{trade.side} {trade.symbol}</b> · {trade.reason || "Decision recorded"}</div>)}{!trades.length && <p className="muted">No recent trading activity.</p>}</div></Card>
  </main>;
}
